export NODE_AUTH_TOKEN="op://dev/github_pat/credential"
export MORPH_API_KEY="op://dev/morph_api_key/password"
export TAVILY_API_KEY="op://dev/tavily_api_key/password"
export ANTHROPIC_API_KEY="op://dev/anthropic_api_key/password"
export LLM_PROXY_API_KEY="op://dev/llm_proxy_api_key/password"
